baseURL = "https://cspapr26.github.io/"
languageCode = "en-us"
title = "0xcsp23"
paginate = 5

[module]
  [[module.imports]]
    path = "github.com/panr/hugo-theme-terminal/v4"

[params]
  # Theme Customization
  themeColor = "green"  # options: orange, blue, red, green, pink
  fullWidthTheme = false
  centerTheme = false
  contentTypeName = "posts"
  showMenuItems = 2

[languages.en]
  title = "0xcsp23"
  subtitle = "Cybersecurity Analyst | Network Defense"
  menuMore = "Show more"

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about"
[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects"
