baseURL = "https://cspapr26.github.io/"
languageCode = "en-us"
title = "0xcsp23"
paginate = 5

[module]
  [[module.imports]]
    path = "github.com/panr/hugo-theme-terminal/v4"

[params]
  # FORCE COLOR HERE
  themeColor = "green"
  fullWidthTheme = false
  centerTheme = false
  contentTypeName = "posts"
  showMenuItems = 2

[languages.en]
  title = "0xcsp23"
  subtitle = "Cybersecurity Analyst"
  menuMore = "Show more"

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about"

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects"
